services:
  - type: web
    name: ced-halaltech
    runtime: node
    buildCommand: npm install --legacy-peer-deps --only=production && npm run build:server-only
    startCommand: npm start
    healthCheckPath: /api/health
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: "10000"
      - key: NPM_CONFIG_AUDIT_LEVEL
        value: "none"
