services:
  - type: web
    name: cedhalaltech-club-empreinte-digitale
    runtime: node
    buildCommand: npm install && npm run build:full
    startCommand: npm start
    healthCheckPath: /api/health
    plan: starter
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: "10000"
